### ISSUE TITLE
거래유형선택

### ISSUE THREAD

**Issue by yeongseon** [Kyeongrok/excel_vba_app_01#10]
경쟁매매 협의매매 종합  = g, h, i열 레이블

**Comment by yeongseon** [comment]
콤보박스에 반영

**Comment by Kyeongrok** [comment]
시작가, 마감가는 '경쟁매매, 협의매매, 전체'와 상관이 없다.
선택한 기간의 '종가'를 기준으로 출력한다.

시작가는 선택된 기간의 첫재날의 종가
마감가는 선택된 기간의 마지막날의 종가
를 출력하면 된다.

**Comment by ECOEYEJINJU** [comment]
네, 맞아요!

**Comment by Kyeongrok** [comment]
기간별, 누적 시작가, 마감가 E열 종가 기준으로 변경
