### ISSUE TITLE
엑셀파일을 열었을 때 보이는 화면 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#12]
엑셀파일을 열었을 때 사용자가 맨 처음 보는 화면(초기값)은 최근 날짜로부터 일주일간의 값이다.

**Comment by Kyeongrok** [comment]
마지막 시트명 ex)KAU17_실적의 '1주일' 버튼을 클릭한 결과 로 수정함
