### ISSUE TITLE
등락률 계산시 오류

### ISSUE THREAD

**Issue by yeongseon** [Kyeongrok/excel_vba_app_01#14]
등략률(%) = (마감가 - 시작가) / 시작가

시작가가 0인경우는 어떻게 처리해야 하는지.

**Comment by ECOEYEJINJU** [comment]
시작가가 0인 경우는 없습니다. 
보내드린 데이터에 0인 경우가 있는지 확인해보고 수정해서 말씀드릴게요!

**Comment by Kyeongrok** [comment]
실제로 시작가가 0으로 나오는 경우가 있을  수 있습니다.

**Comment by Kyeongrok** [comment]
https://github.com/Kyeongrok/excel_vba_app_01/issues/10 에서 해결하면 해결될 이슈라서 close처리함
