### ISSUE TITLE
차트 이슈

### ISSUE THREAD

**Issue by yeongseon** [Kyeongrok/excel_vba_app_01#16]
![image](https://user-images.githubusercontent.com/8798819/32177727-5e8feb88-bdce-11e7-88db-5672c7cd1670.png)

차트를 그릴 때 데이터가 없는 구간에도 표시됨

**Comment by ECOEYEJINJU** [comment]
차트를 그릴 때 데이터가 없는 구간에는 표시되지 않게 수정해주세요

**Comment by Kyeongrok** [comment]
없는 구간은 표시 안되게 수정
ActiveChart.Axes(xlCategory).CategoryType = xlCategoryScale
