### ISSUE TITLE
차트 축 종가, 거래량(톤) 종합

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#2]

**Comment by ECOEYEJINJU** [comment]
차트의 X축은 날짜이고, Y축의 왼쪽은 거래량, 오른쪽은 가격이다.
X축 날짜의 표시형식은 yyyy/mm/dd이다.
Y축의 왼쪽 거래량의 단위는 '천톤'이다.
**-> 데이터에서 거래량이 톤단위로 되어있는데요, 천톤단위로 계산해서 올릴까요?  그래프는 천톤단위로 나타나지만, 아래 '누적거래현황'과 '기간별거래현황'에는 톤단위로 표시하려고 하는데요, 열을 추가해서 천톤단위로 계산한 것 추가하면 되나요?**

Y축의 오른쪽 가격의 단위는 '원'이다.

**Comment by ECOEYEJINJU** [comment]
그래프에서 보여지는 날짜는 아직 가로로 보여지는 것이 좋을지, 세로 또는 대각선으로 보여지는 게 좋을지 정해지지 않았고, 날짜가 보여지는 간격(1주일 간격, 2달 간격 등)도 아직 정해지지 않았습니다!

**Comment by Kyeongrok** [comment]
그래프에서 보여지는 날짜는 각 기간별로 텀을 조정하여 가로 또는 대각선으로 보이게 수정함
