### ISSUE TITLE
시작가가 0으로 나오는 경우가 있습니다.

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#28]
이거 한번 확인 바래요

현재 데이터를 보면 나올 가능성이 충분히 있어서요.

**Comment by ECOEYEJINJU** [comment]
네, 확인해보겠습니다!

**Comment by ECOEYEJINJU** [comment]
선생님, 시작가는 시가, 종가 할때의 시가를 의미하는 건가요?

**Comment by Kyeongrok** [comment]
경쟁매매, 협의매매, 종합 여기에서 '시작가'요

**Comment by Kyeongrok** [comment]
https://github.com/Kyeongrok/excel_vba_app_01/issues/10 에서 해결하는 걸로 한다
