### ISSUE TITLE
ui 모양 수정사항

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#30]
![image](https://user-images.githubusercontent.com/1642243/32314772-b79100c6-bfec-11e7-9577-371dd9195ca9.png)

**Comment by Kyeongrok** [comment]
1.#35에서 수정
2.지난번 수정 했는데 git에 반영을 하지 않아서 이번에 반영함
3.#34에서 수정
4.지난번 수정 했는데 git에 반영을 하지 않아서 이번에 반영함
6.지난번 수정 했는데 git에 반영을 하지 않아서 이번에 반영함

**Comment by yeongseon** [comment]
(천톤), (원) 위치 수정 해야 함.

**Comment by Kyeongrok** [comment]
축제목 천톤, 원 위치 절대값으로 조정함
'축 제목 위치
    With ActiveChart.Axes(xlValue).AxisTitle
        .Left = 55
        .Top = 16
    End With
    
    With ActiveChart.Axes(xlValue, xlSecondary).AxisTitle
        .Left = 890
        .Top = 16
    End With
