### ISSUE TITLE
1주일, 1월 ··· 누르면 아래 ComboBox "경쟁 매매"로 초기화 할 것

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#36]
현재 협의 매매를 선택하고
기간을 버튼으로 선택하면
경쟁매매 가격이 보이지만 콤보박스는 협의 매매로 보임

**Comment by yeongseon** [comment]
Sheets("dashboard").ComboBox2.Value = "경쟁매매"
