### ISSUE TITLE
수정사항 총정리 1 입니다.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#38]
![image](https://user-images.githubusercontent.com/32359719/32493677-0bd2cf7a-c402-11e7-9415-17aaaee76f37.png)

**Comment by Kyeongrok** [comment]
천톤 -> 톤으로 변경 하는것만 해드리겠습니다.나머지 서식은 직접 수정 가능하십니다

**Comment by Kyeongrok** [comment]
제목은 시트명을 따라가게 해놓았습니다 시트명을 수정해주세요

**Comment by Kyeongrok** [comment]
x축 좌우 축은 한번 변경 해드렸습니다

**Comment by Kyeongrok** [comment]
오류가 없으면 더이상은 해드릴 수 없습니다 계약서에 나온것 이상으로 공수를 많이 썼습니다
