### ISSUE TITLE
텍스트 삽입관련 문의드려요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#40]
표 밑에 
*기간별 거래현황 : 기간 선택 버튼 또는 기간 설정 박스에서 지정한 기간의 거래현황
*누적거래현황 : 상장일 또는 첫 일로부터 기간 선택 버튼 또는 기간 설정 박스에서 지정한 기간 마지막일까지의 거래현황
이라고 설명을 추가할 예정이에요. 코드로 입력하셔야 하나요? 아니면 저희가 추가하면 되나요?
확인해주세요.

**Comment by Kyeongrok** [comment]
텍스트는 직접 추가하시면 됩니다.
