### ISSUE TITLE
KCU, KOC 그래프 색깔은 각각 다르게 할 예정입니다.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#41]
KCU와 KOC의 그래프 색깔은 각각 다르게 할 예정이에요. 
곧 색상 코드 보내드리겠습니다.
이 작업 착수는 언제하시나요?

**Comment by Kyeongrok** [comment]
색상은 한번 변경 해드려서 이번 프로젝트 끝나고 추가로 요청해주세요.
