### ISSUE TITLE
다른 시트와의 결합 여부

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#42]
현재 저희가 배포하는 엑셀파일이 있는데, 그것과 합칠 수 있나요?
업무 초반에 선생님께서 된다고 답변해 주신것으로 기억하는데, 내부적으로 다시 한번 확인해 달라는 요청이 있어서 다시 질문드려요.

**Comment by Kyeongrok** [comment]
다른 파일에 가능은 하지만 이번에는 어렵습니다.
