### ISSUE TITLE
그래프 내 이행연도 구분 가능 여부

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#43]
![image](https://user-images.githubusercontent.com/32359719/32493973-29d3f084-c403-11e7-8e5e-353540f99289.png)
KAU연결 시트는 2015년부터 2017년까지 거래가격과 거래량이 보여지는데, 매년 일정 기간을 기준으로 '이행연도'라는 용어로 구분이 되요. 해당 그래프에서 구현이 가능한가요?(그림에서 가운데 파란색 점선)

**Comment by Kyeongrok** [comment]
가능은 한데 어려울것 같습니다.
