### ISSUE TITLE
기능 추가 가능 여부 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#44]
![image](https://user-images.githubusercontent.com/32359719/32494097-a4e2c822-c403-11e7-912b-c0abeb24a30c.png)
이것도 작업 초반에 선생님이 안된다고 말씀해 주신것으로 기억하는데요, 그래프 내 어떤 일자에 마우스 커서를 대면 위 그림과 같이 거래량과 가격이 나올 수 있게 구현이 가능한지 내부적으로 다시 한번 더 확인해 달라는 요청이 있었어요. 가능하다면 추가로 비용은 얼마나 소요되는지도 말씀해주세요.

**Comment by Kyeongrok** [comment]
이번 일이 끝난 후에 문의 주세요. 검토 하는 것도 공수가 들어갑니다.
