### ISSUE TITLE
전체를 선택하면 경쟁매매 + 협의매매가 나오게 수정

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#47]

**Comment by yeongseon** [comment]
현재 거래유형선택에서 전체를 선택시에는 실적에서 I열을 기준으로 기간별거래현황, 누적거래현황을 계산하고 있음.
전체 선택시 경쟁매매 + 협의매매 에 대한 상세 설명 필요.

**Comment by ECOEYEJINJU** [comment]
예를들면, 
현재 거래종목에서 KAU17을 선택하고 3개월버튼을 누르면 7월17일부터 10월17일까지의 데이터로 표에 나온 항목들이 계산되어 나옵니다. 이때 경쟁매매는 KAU17탭의 G열 기준, 협의매매는 H열 기준, 전체는 I열 기준입니다. 
경쟁매매의 거래량은 682,199, 협의매매의 거래량은 677,535, 전체 거래량은 경쟁매매와 협의매매 거래량이 합쳐진 1,359,734입니다. 그런데 현재는 전체 거래량이 경쟁매매 거래량과 동일하게 나오고 있으며, 평균매매가, 거래대금 역시 경쟁매매의 것과 동일하게 나오고 있습니다. 다시 한번 확인 부탁드립니다.

**Comment by yeongseon** [comment]
If pExchangeTypeName = "경쟁매매" Then
        columnAddressTon = "G"
        columnAddressWon = "J"
    ElseIf pExchangeTypeName = "협의매매" Then
        columnAddressTon = "H"
        columnAddressWon = "K"
    ElseIf pExchangeTypeName = "전체" Then
        columnAddressTon = "I"
        columnAddressWon = "L"
    End If
