### ISSUE TITLE
행 삽입이 필요합니다.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#48]
![image](https://user-images.githubusercontent.com/32359719/32534630-c89ec6ee-c499-11e7-8f7f-382609a10be4.png)
위의 그림과 같이 그래프 제목이 들어갈 행을 추가해야 해요. 
애초에 말씀드리지 못해 죄송해요ㅠ_-..
행 높이는 그림에 나타난것으로 계산하면 1행부터 4행까지 각 34.2 / 34.2 / 17.4 / 17.4으로 총 103.2이에요.
한 행을 추가해서 103.2로 해주셔도 되고 위의 그림처럼 해주셔도 되고 어떻게든 공간을 만들 수 있다면 상관없어요!

**Comment by Kyeongrok** [comment]
4행 추가하는걸로 수정 예정입니다.

**Comment by Kyeongrok** [comment]
하단 표 출력 하는 로직도 다 +4씩 되어야함
