### ISSUE TITLE
누적의 기준

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#5]
누적은 시트의 2번행의 a1에 있는 날짜 부터
ui에 기간을 선택 했을때 바뀌는 to 날짜까지다

**Comment by ECOEYEJINJU** [comment]
누적의 기준 확정됐습니다*-*
선생님이 써두신대로 하기로 했어요!
예) KAU16의 전체 거래 기간은 2016.7.1~2017.6.30이다
이 때, 기간 설정을 2016.8.2~2016.9.23 으로 했다면, 
기간별 거래현황은 2016.8.2~2016.9.23 의 데이터가 집계되고, 
누적 거래현황은 2016.7.1~2016.9.23 의 데이터가 집계된다.

**Comment by ECOEYEJINJU** [comment]
누적의 기준 확정됐습니다*-*
선생님이 써두신대로 하기로 했어요!
예) KAU16의 전체 거래 기간은 2016.7.1 부터 2017.6.30 까지이다
이 때, 기간 설정을 2016.8.2 부터 2016.9.23 까지로 했다면, 
기간별 거래현황은 2016.8.2 부터2016.9.23 까지의 데이터가 집계되고, 
누적 거래현황은 2016.7.1 부터 2016.9.23 까지의 데이터가 집계된다.
