### ISSUE TITLE
데이터 보여주는 표(테이블) 중 누적거래현황 위치를 상단 그래프가 끝나는 끝점과 맞추어주세요

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#51]
데이터 보여주는 표(테이블) 중 누적거래현황 위치를 상단 그래프가 끝나는 끝점과 맞추어주세요.
지난번에 현장에서 같이 맞추었던 것 같은데 다시 달라져 있습니다~!

**Comment by Kyeongrok** [comment]
이건 스크린샷을 올려주시면 수정 해드리겠습니다.

**Comment by Kyeongrok** [comment]
![kakaotalk_20171117_152454681](https://user-images.githubusercontent.com/1642243/32932523-b2765f94-cbab-11e7-95b1-8f5ddd399d7e.png)
