### ISSUE TITLE
그래프 하단의 표(테이블)에서 글자(시작가, 마감가, 등락률 등) 가운데 정렬 해주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#53]
그래프 하단의 표(테이블)에서 글자(시작가, 마감가, 등락률 등) 가운데 정렬 부탁드립니다.
숫자는 오른쪽 정렬이 맞는데, 글자는 왼쪽정렬이 아니라 가운데 정렬 부탁드립니다.

**Comment by Kyeongrok** [comment]
가운데 정렬 하였습니다.

**Comment by pinoalto** [comment]
감사합니다. 확인했습니다
