### ISSUE TITLE
현재 [일주일]을 선택하면 6개 날짜가 보이는데 5개 날짜로 해주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#54]
현재 최신 데이터가 화요일까지로 되어 있어 이렇게 보이는지 모르겠지만,

현재 최신 6일의 정보가 보입니다.

지난번에 월-금 5개로 협의하였습니다. 이 부분 수정 부탁드립니다

**Comment by Kyeongrok** [comment]
Module.startDate = DateAdd("d", -7, Module.endDate)
현재 -7로 되어있습니다. 예를들어 마지막 행이 11.17인 경우 11.10~11.17까지 보이게 되어 있습니다.
이걸 -4로 바꿔서 11.13~11.17까지 보이게 해드리면 될까요?

**Comment by Kyeongrok** [comment]
-4로 변경 하였습니다.

**Comment by pinoalto** [comment]
네 확인했습니다
