### ISSUE TITLE
"KAU 연결"에서 [전체]를 설정하면 날짜가 수직으로 서는데 대각선으로 비스듬하게 만들어주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#55]
"KAU 연결"에서 [전체]를 설정하면 날짜가 수직으로 서는데 대각선으로 비스듬하게 서도록 만들어주세요.

**Comment by Kyeongrok** [comment]
해당 값을 정할 수는 있으나 데이터 개수에 따라서 다시 바뀔 수 있어서 이 이슈는 수정하기 어렵습니다.
