### ISSUE TITLE
"KAU 17"에서 [전체]를 선택하면 x축 날짜가 수평으로 눕는데 대각선으로 세워주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#56]
"KAU 17"에서 [전체]를 선택하면 x축 날짜가 수평으로 눕는데 비스듬하게 대각선으로 세워주세요.

**Comment by yeongseon** [comment]
KAU15, KAU16 의 경우는 데이터가 360개이상이고, KAU17의 경우는 데이터나 178개라서 발생하는 문제

**Comment by pinoalto** [comment]
네 확인했습니다

**Comment by pinoalto** [comment]
KAU17에서 1개월, 3개월, 6개월, 1년 선택시에는 [전체]보다 데이터 수가 적지만 대각선으로 서서 보입니다. 데이터 수가 KAU15, 16보다 적어서 발생하는 문제는 아닌 것 같은데, 확인 부탁드립니다.
