### ISSUE TITLE
"KAU 16" 에서 [전체] 선택했을 때 기간별 값과 누적 값이 같아야 하는데 차이가 납니다.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#57]
"KAU 16" 에서 [전체] 선택했을 때 기간별 값과 누적 값이 같아야 하는데 차이가 납니다.
오류 수정 부탁드립니다.

**Comment by yeongseon** [comment]
KAU 16에 2016년 8월 24일, 2016년 9월 21일 데이터 포맷이 yyyy/mm/dd로 되어 있습니다.
데이터 소스는 yyyy-mm-dd로 표기되어야 합니다.
데이터 수정함.

**Comment by pinoalto** [comment]
네 확인했습니다. 감사합니다~
