### ISSUE TITLE
시트별로 타이틀에서 언더바를 삭제해주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#58]
KAU_연결 → KAU 연결
KAU15_실적 → KAU15
KAU16_실적 → KAU16
KAU17_실적 → KAU17

이렇게 변경부탁드립니다.
만약 여기서 수정할 수 있는 부분이면 수정하는 방법을 알려주시면 제가 하도록 하겠습니다.

**Comment by Kyeongrok** [comment]
이건 시트명을 변경해주세요. 시트명 변경 하시고 저장하고 다시 켜시면 바뀌어 있습니다.

**Comment by Kyeongrok** [comment]
수정 하였습니다.

**Comment by pinoalto** [comment]
확인했습니다
