### ISSUE TITLE
기간버튼 눌렀을때 날짜가 선택되는 기준

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/excel_vba_app_01#6]
은
해당 시트의 가장 마지막 열 -7부터 열의 날짜까지다

**Comment by Kyeongrok** [comment]
월은 month -1하면 됨

**Comment by ECOEYEJINJU** [comment]
1주일은 사용자가 파일을 여는 날이 기준이 아니라,
가장 최근 데이터가 있는 주의 월요일부터 금요일까지이다.
예를 들어, 2017년 10월 13일(금)이 가장 최근 데이터라면, 10월 9일(월)부터 10월 13일(금)까지의 데이터를 1주일로 한다. 이 때, 9일은 휴장일이므로 데이터가 없다. 따라서 그래프에 보여지는 값은 10일(화)부터 13일(금)까지이다. 
1개월은 다음과 같다. 
예를 들어, 2017년 10월 13일(금)이 가장 최근 데이터라면, 1개월은 9월 14일부터 10월 13일까지로 한다. 
3개월은 7월 14일부터 10월 13일까지이다. 
6개월은 4월 14일부터 10월 13일까지이다. 
위에 날짜처럼 보여지게 한다면, month -1 혹은 -n일 등 수식은 선생님께서 가능하신 것으로 해주세요!

**Comment by Kyeongrok** [comment]
시트의 맨 마지막 행 기준 -4 day, -1, -3, -6 month, -1 year, 전체 이렇게 변경하였습니다.

**Comment by ECOEYEJINJU** [comment]
네, 알겠습니다!
