### ISSUE TITLE
y축 그래프 모양을 바꿔주세요.

### ISSUE THREAD

**Issue by pinoalto** [Kyeongrok/excel_vba_app_01#62]
'원'에 해당하는 그래프-선그래프
'톤'에 해당하는 그래프-막대그래프

감사합니다.

**Comment by Kyeongrok** [comment]
![kakaotalk_20171120_110830365](https://user-images.githubusercontent.com/1642243/32999089-83d915ac-cde3-11e7-883d-4a870a0752e5.png)
로 수정했습니다.

![kakaotalk_20171120_111002663](https://user-images.githubusercontent.com/1642243/32999090-85f00918-cde3-11e7-9b0f-7c5139b1b44b.png)
는 이전꺼입니다.
