### ISSUE TITLE
KCU, KOC 추가해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#63]
KCU(KCU/KCU15/KCU16/KCU17) 및 KOC 그래프 추가를 부탁드립니다.

**Comment by Kyeongrok** [comment]
KOC추가 하였습니다.

**Comment by ECOEYEJINJU** [comment]
선생님, 조금 아까 올려주신것은 KCU이고 KOC도 추가가 필요합니다.

**Comment by Kyeongrok** [comment]
파일 하나 복사해서 데이터가 들어있는 시트를 지우시고 한번 넣어보세요.
제가 해드려도 금방이긴 한데 KCU가 이상이 없다면 한번 해보시기 바랍니다.
안되시면 제가 해드릴게요.

**Comment by ECOEYEJINJU** [comment]
네, 해보고 말씀드릴게요!

**Comment by ECOEYEJINJU** [comment]
선생님, 올려주신 KCU 확인하고, KOC 추가해보았는데요. 잘 된건지 확인 부탁드려요. 
그리고 KCU에서 오른쪽 Y축(톤)이 기간별 버튼을 눌렀을 때 일부 1과 0으로 표기되고 있어요. KOC도 동일한 문제가 발생하는데 확인 부탁드려요.

**Comment by Kyeongrok** [comment]
현재 거래량(톤) 종합 데이터가 다 0으로 들어가있어서 그래프가 안나오고 있구요

최대값 최소값은 데이터에 따라 자동으로 정해지는데 지금은 최대값이 1로, 최소값이 0으로 정해져 있어서 저렇게 나와요.

**Comment by Kyeongrok** [comment]
KOC는 열어보았는데 조회 잘 되는것 같아요. 예상치와 다르게 나오는게 있다면 알려주세요.

**Comment by ECOEYEJINJU** [comment]
네 이해했습니다. 
다른 것도 다시 한번 보고 궁금한 것이나 다르게 나오는 것들 말씀드릴게요. 
고생하셨습니다. 고맙습니다.

**Comment by ECOEYEJINJU** [comment]
선생님, 궁금한게 있어요. 
방금 테스트(1121)이라는 파일을 올렸는데요, KAU, KCU, KOC를 하나의 엑셀에 모았고, 저희가 필요한 나머지 정보제공시트들도 합쳤습니다. 
그리고, 그래프 화면 외 filter시트와 데이터 시트는 다 숨기기를 해 둔 상태입니다.
여기서 문제가 생기는데요, KAU그래프가 있는 시트의 제목은 dashboard, KCU그래프 시트 제목은 dashboard(2), KOC 그래프 시트 제목은 dashboard(3)이에요. 
숨기기까지 했을때는 기능에 이상 없이 그래프가 잘 나타났는데, 각 그래프가 들어있는 시트의 명칭을 변경했더니 오류가 나온다고 팝업창이 뜹니다. 
명칭이 변경되서 그런것인지 아니면 제가 다른 것을 건드려서 그런것인지, 어떻게 해결해야 할지 궁금합니다. 
또 하나는, KCU 그래프와 KOC 그래프에서 기간설정 버튼을 누르거나 종목을 변경하면 KAU 시트로 화면이(시트가) 넘어갑니다. 
확인 부탁드릴게요. 고맙습니다.

**Comment by Kyeongrok** [comment]
네 해당 작업을 하면 이렇게 작동합니다.
파일 하나에 3개 dashboard를 꼭 만드셔야 하나요?
그러면 추가 작업을 좀 더 해야 합니다.

**Comment by ECOEYEJINJU** [comment]
네, 선생님. 저희 회사 회원사에 방금 올린 것처럼 배포할 예정이어서 꼭 합쳐야만 해요. 
시간이 조금 더 소요되어도 꼭 부탁드려요.

**Comment by Kyeongrok** [comment]
dashboard n번째
indexOf KAU, KCU, KOC로 sheet import

**Comment by ECOEYEJINJU** [comment]
시트 제목은 KAU그래프 시트는 거래추이(KAU), KCU그래프 시트는 거래추이(KCU), KOC그래프 시트는 거래추이(KOC)로 부탁드려요.

**Comment by Kyeongrok** [comment]
이거 추가함
