### ISSUE TITLE
기간설정박스에서 기간을 설정함에 따른 X축 날짜 모양을 대각선으로 바꿔주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#65]
기간설정박스에서 기간을 설정하면, 대각선이었던 X축 날짜가 수직으로 보여집니다. 구간도 너무 촘촘합니다. 대각선으로 보이고, 어느정도의 간격이 있을 수 있도록 수정해주세요.

**Comment by Kyeongrok** [comment]
완료
