### ISSUE TITLE
누적거래현황에 오류가 있습니다. 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#66]
누적거래현황은 기간설정박스에서 지정한 기간의 마지막일까지의 거래현황인데, 현재는 데이터 상 마지막 일까지로 누적이 보여집니다. 수정해주세요.

**Comment by Kyeongrok** [comment]
검색 버튼 눌렀을때만 이 이슈가 발생함 수정함
