### ISSUE TITLE
엑셀 시트 첫 화면 오류와 데이터 삽입하고 난 후 오류 수정해주세요. 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#68]
![image](https://user-images.githubusercontent.com/32359719/33162524-3cf2552c-d06d-11e7-9054-f7699cd52eec.png)

엑셀 파일 열었을때, dashboard(KAU 그래프시트) 첫화면은 일주일 데이터로 잘 보입니다. 
dashboard(2)(KCU 그래프 시트)와 dashboard(3)(KOC 그래프 시트)의 첫화면이 위의 그림과 같이 나와요. 
수정 부탁드려요. 

![image](https://user-images.githubusercontent.com/32359719/33162641-ed9eb56e-d06d-11e7-9955-785cd457aec1.png)

그 전에, 제가 KCU 데이터를 추가하고 저장 후, 다시 파일을 열었는데 위의 그림처럼 오류 팝업이 뜹니다. 확인해주시고 수정 부탁드려요.

**Comment by Kyeongrok** [comment]
수정했습니다.
