### ISSUE TITLE
KOC 기간설정 박스에 기간을 입력하면 뜨는 오류 수정해주세요. 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#69]
KOC 시간설정 박스에 기간을 입력하고 조회버튼을 눌렀는데, 다음과 같은 오류 팝업창이 나오고 적용이 되지 않았어요. 수정 부탁드려요. 
![image](https://user-images.githubusercontent.com/32359719/33162684-314e2ef2-d06e-11e7-81d3-c1bb53710467.png)

**Comment by Kyeongrok** [comment]
수정했어요
