### ISSUE TITLE
그래프에 들어가는 데이터

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#7]
시트별로 그래프와 표에 들어가는 데이터 정리했어요.
KAU '거래종목'에서 선택하여 볼 수 있는 각 탭별 데이터 - KAU종합 / KAU15 / KAU16 / KAU17
KCU '거래종목'에서 선택하여 볼 수 있는 각 탭별 데이터 - KCU종합 / KCU15 / KCU16 / KCU17
KOC는 '거래종목' 선택 없음

**Comment by yeongseon** [comment]
필요데이터 정리파일
