### ISSUE TITLE
dashboard, dashboard(2), dashboard(3) 명칭 변경 문의드려요. 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#70]
dashboard, dashboard(2), dashboard(3)명칭을 각각 거래추이(할당), 거래추이(상쇄), 거래추이(외부사업 인증량) 으로 바꾸려고 하는데요. KAU로 중복되는 것이 없으니 가능할까요? 가능하다면 제가 바꾸면 될까요?

**Comment by Kyeongrok** [comment]
수정했습니다

**Comment by ECOEYEJINJU** [comment]
선생님.. Dashboard(3)시트 제목 외부산업을 외부사업으로 수정해주세요..!

**Comment by Kyeongrok** [comment]
수정했습니다.
