### ISSUE TITLE
파일을 열었을 때 발생하는 오류 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#71]
![image](https://user-images.githubusercontent.com/32359719/33198666-dbccd6b4-d12f-11e7-8f2b-6abe0bd40857.png)

어제 올려주신 파일을 확인해 보려고 파일을 열었는데, 위와 같은 창이 뜹니다. 
수정 부탁드려요.

**Comment by Kyeongrok** [comment]
수정했습니다.

**Comment by ECOEYEJINJU** [comment]
고맙습니다*-*!
