### ISSUE TITLE
누적거래현황 표 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#72]
예시 1. 기간선택버튼을 누른 경우.
예를들어 존재하는 전체데이터가 2015.01.01 - 2017.11.30 일때,
1개월 버튼을 누르면, 기간별거래현황 표에는 2017.10.30 - 2017.11.30까지의 값이 나오고(이건 이상 없어요), 누적거래현황 표에는 2015.01.01 - 2017.11.30의 값이 나와야합니다. 지금은 기간별거래현황 표와 같은 값이 나오고 있어요.

예시2. 기간설정박스에 날짜를 직접 입력한 경우.
예를들어 존재하는 전체데이터가 2015.01.01-2017.11.30 일때,
날짜 입력을 2016.10.20-2017.02.03 라고 하면,
기간별거래현황 표에는 2016.10.20-2017.02.03까지의 값이 나오고(이상없어요!), 누적거래현황 표에는 2015.01.01-2017.02.03까지의 값이 나와야 해요.

즉, 기간선택버튼(1주일, 1개월, 3개월 등)을 누르면 마지막일 조정이 불가(전체데이터의 마지막 일이 기준이므로)하기 때문에 누적거래현황에는 전체데이터의 첫일부터 마지막일까지가 모두 보이는것이고,
기간설정박스에서는 마지막일자를 바꿀수 있기 때문에 전체데이터의 첫일부터 기간설정박스에 기입한 마지막일자까지의 데이터가 보여져야 해요. 전체데이터의 첫일은 고정인 것이지요.

그리고 현재 기간설정박스에 기간을 입력하고 조회버튼을 누르면, 아래 표 값이 바뀌는데. 그리고 나서 기간선택버튼을 눌러 다른 기간값을 보려고 하면!
기간별거래현황표는 바뀌지만 누적거래현황표는 바뀌지 않고 있어요. 확인 부탁드려요.

**Comment by Kyeongrok** [comment]
수정 하였습니다.
