### ISSUE TITLE
그래프 깨짐 현상 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#73]
![image](https://user-images.githubusercontent.com/32359719/33308896-945968e6-d45f-11e7-9462-5c3a0efc7134.png)

엑셀을 열고, '거래추이(외부사업)'에서 기간 조회 등 조작을 하고 '거래추이(할당)' 탭으로 돌아오면 그래프가 깨지는 현상이 나타납니다. 수정 부탁드려요.

**Comment by Kyeongrok** [comment]
이슈 재현이 아니 되옵니다.

**Comment by Kyeongrok** [comment]
데이터 시트의 날짜 형식이 제대로 설정 안된경우 발생하는 걸로 보입니다.
문서를 열 때 데이터 시트의 A열 표시형식을 날짜로 지정하게 변경하였습니다.
