### ISSUE TITLE
기간 설정에 따른 기간 표시 수정해주세요. 

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#74]
![image](https://user-images.githubusercontent.com/32359719/33308957-cceaa4e0-d45f-11e7-81f0-1828970a1f09.png)

기간설정박스에서 날짜를 기입하고 조회버튼을 누르면, 
아래 기간별거래현황의 기간과 누적거래현황에 나타나요. 
그리고 나서 다른 기간을 보기 위해 기간 버튼을 누르면, 기간 설정박스의 날짜와 기간별거래현황표의 기간은 변경되는데, 누적거래현황의 기간은 변경되지 않아요. 
수정해주세요.

**Comment by Kyeongrok** [comment]
해당 이슈 수정 했습니다.
