### ISSUE TITLE
하단 표 거래유형 선택 시, 누적거래현황표의 값 오류 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#75]
![image](https://user-images.githubusercontent.com/32359719/33407642-aa6b59c6-d5b5-11e7-962e-a44c936fa91a.png)

KAU, KCU, KOC에서 모두 발생하는 문제인데요.
기간설정박스에서 기간을 입력한 후, 조회버튼을 누르면 하단 표인 '기간별거래현황', '누적거래현황' 모두 값이 잘 계산되어 나와요. 
그런데, 거래유형 선택에서 경쟁매매, 협의매매를 선택하면 누적거래현황표의 값이 전체 데이터의 첫날부터~기간설정박스에서 선택한 마지막날짜 까지가 아닌 전체 데이터에 대한 계산값이 나오고 있어요(2017-01-23 - 2017-10-25(예시)를 대상으로 값이 산출되어 나와야 하는데, 경쟁, 협의를 누르면 2017-01-23 - 2017-11-24 까지 계산되어 나오는거죠!). 엑셀로 직접 계산해보았고, 이미지에 예시를 적어서 올려드려요. 확인 부탁드려요.

**Comment by Kyeongrok** [comment]
수정했습니다.
