### ISSUE TITLE
기간설정박스에서 날짜 입력하여 조회 후, 기간버튼 누르면 생기는 오류 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#76]
![image](https://user-images.githubusercontent.com/32359719/33407821-72a7b89e-d5b6-11e7-9cd7-f7a95a79857e.png)

기간설정박스에서 기간을 입력한 후, 조회버튼을 누르고 값을 확인한 후에 기간버튼을 누르면 기간설정박스의 기간은 변경되지만 누적거래현황표의 기간은 변경되지 않고 있어요. 
표 안의 값은 누른 기간버튼의 값에 따라 문제 없이 산출되고 있어요. 확인 부탁드려요.

**Comment by Kyeongrok** [comment]
수정했습니다.
