### ISSUE TITLE
파일을 열었을 때 생기는 오류 수정해주세요.

### ISSUE THREAD

**Issue by ECOEYEJINJU** [Kyeongrok/excel_vba_app_01#77]
![image](https://user-images.githubusercontent.com/32359719/33415632-1583982a-d5db-11e7-9ce4-a7fc6acb9c33.png)

오늘 수정해주신 파일을 열었는데, 다음과 같은 화면이 나타나요. 수정해 주세요.

**Comment by Kyeongrok** [comment]
수정했습니다.
